name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:




  main_clone:
    title: Cloning main repository...
    stage: checkout
    type: git-clone
    repo: 'cruiz24-HackTober_2020'
    revision: master
    git: github
  compile_my_sources:
    title: Compile
    stage: build
    image: gcc
    commands:
      - make
  run_my_tests:
    title: Test
    stage: build
    image: gcc
    commands:
      - make test   
